/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiButton {
        "disabled": boolean;
        "type": string;
    }
    interface UiHeadline {
    }
    interface UiMain {
    }
}
declare global {
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiHeadlineElement extends Components.UiHeadline, HTMLStencilElement {
    }
    var HTMLUiHeadlineElement: {
        prototype: HTMLUiHeadlineElement;
        new (): HTMLUiHeadlineElement;
    };
    interface HTMLUiMainElement extends Components.UiMain, HTMLStencilElement {
    }
    var HTMLUiMainElement: {
        prototype: HTMLUiMainElement;
        new (): HTMLUiMainElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUiButtonElement;
        "ui-headline": HTMLUiHeadlineElement;
        "ui-main": HTMLUiMainElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
        "disabled"?: boolean;
        "type"?: string;
    }
    interface UiHeadline {
    }
    interface UiMain {
    }
    interface IntrinsicElements {
        "ui-button": UiButton;
        "ui-headline": UiHeadline;
        "ui-main": UiMain;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-headline": LocalJSX.UiHeadline & JSXBase.HTMLAttributes<HTMLUiHeadlineElement>;
            "ui-main": LocalJSX.UiMain & JSXBase.HTMLAttributes<HTMLUiMainElement>;
        }
    }
}
