/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiButton {
    }
    interface UiHeadline {
    }
    interface UiText {
    }
}
declare global {
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiHeadlineElement extends Components.UiHeadline, HTMLStencilElement {
    }
    var HTMLUiHeadlineElement: {
        prototype: HTMLUiHeadlineElement;
        new (): HTMLUiHeadlineElement;
    };
    interface HTMLUiTextElement extends Components.UiText, HTMLStencilElement {
    }
    var HTMLUiTextElement: {
        prototype: HTMLUiTextElement;
        new (): HTMLUiTextElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUiButtonElement;
        "ui-headline": HTMLUiHeadlineElement;
        "ui-text": HTMLUiTextElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
    }
    interface UiHeadline {
    }
    interface UiText {
    }
    interface IntrinsicElements {
        "ui-button": UiButton;
        "ui-headline": UiHeadline;
        "ui-text": UiText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-headline": LocalJSX.UiHeadline & JSXBase.HTMLAttributes<HTMLUiHeadlineElement>;
            "ui-text": LocalJSX.UiText & JSXBase.HTMLAttributes<HTMLUiTextElement>;
        }
    }
}
